In [1]:
"""Modules"""

import numpy as np
import matplotlib.pyplot as plt

In [11]:
"""Classes"""

class FCC:
    """
    Creates an object (whatever the user defines 'self' as) that has tied to it the array of points that are in an FCC
    lattice as well as the vectors needed that create that lattice from a superposition of basis vectors.
    
    a, float: The value of the lattice constant along the x axis of the crystal geometry.
    b, float: The value of the lattice constant along the y axis of the crystal geometry.
    c, float: The value of the lattice constant along the z axis of the crystal geometry.
    basis_vectors, list/array: A list/array of the points that can be used to construct the 'lattice_vectors.'
    lattice_points, list/array: A list/array of the points that make up the lattice.
    lattice_vectors, list/array: A list/array of the vectors that can be used to construct the lattice.
    """
    
    def __init__(self, a, b, c):
        """
        # a, float: The value of the lattice constant along the x axis of the crystal geometry.
        # b, float: The value of the lattice constant along the y axis of the crystal geometry.
        # c, float: The value of the lattice constant along the z axis of the crystal geometry.
        
        Initializes the FCC crystal lattice object tied to whatever variable the user defines 'self' as.
        
        """
        
        self.a = a
        self.b = b
        self.c = c
        self.basis_vectors = [[a/2, b/2, 0], [a/2, 0, c/2], [0, b/2, c/2]]
        self.lattice_points = [[0, 0, 0], [a, 0, 0], [0, b, 0], [0, 0, c], [a, b, 0], [a, 0, c], [0, b, c], [a, b, c],
                               [a/2, b/2, 0], [a/2, 0, c/2], [0 , b/2, c/2], [a/2, b/2, c], [a/2, b, c/2], [a, b/2, c/2]]
        self.lattice_vectors = []
        
    def lat_vec(self):
        """
        Returns: a/an list/array of the vectors needed to translate to every lattice point from one lattice point. These
        lattice points can also be used to create the lattice if one starts at one of the bottom corners of the lattice.
        """
        
        # Goes through the coordinates in the list 'lattice_points' to create integers that the basis vectors must be
        # multiplied by to create the list/array 'lattice_vectors.'
        for i in range(len(self.lattice_points)):
            q, r, s = self.lattice_points[i][0], self.lattice_points[i][1], self.lattice_points[i][2]
            l, m, n = (s - r - q) / self.a, (r - q - s) / self.b, (q - r - s) / self.c
            # The line below needs some work but it is late and I want to go to bed.
            self.lattice_vectors.append((l * np.array(self.basis_vectors[0]), m * np.array(self.basis_vectors[1]),
                                         n * np.array(self.basis_vectors[2])))
        
        return np.array(self.lattice_vectors)

In [12]:
"""Functions"""

def epsilon():
    """
    Creates the energy dispersion function that will then be plotted along certain k values.
    """
    
    pass

In [13]:
fcc = FCC(0.352, 0.352, 0.352)
print(fcc.lat_vec())

[[[ 0.     0.     0.   ]
  [ 0.     0.     0.   ]
  [ 0.     0.     0.   ]]

 [[-0.176 -0.176 -0.   ]
  [-0.176 -0.    -0.176]
  [ 0.     0.176  0.176]]

 [[-0.176 -0.176 -0.   ]
  [ 0.176  0.     0.176]
  [-0.    -0.176 -0.176]]

 [[ 0.176  0.176  0.   ]
  [-0.176 -0.    -0.176]
  [-0.    -0.176 -0.176]]

 [[-0.352 -0.352 -0.   ]
  [ 0.     0.     0.   ]
  [ 0.     0.     0.   ]]

 [[ 0.     0.     0.   ]
  [-0.352 -0.    -0.352]
  [ 0.     0.     0.   ]]

 [[ 0.     0.     0.   ]
  [ 0.     0.     0.   ]
  [-0.    -0.352 -0.352]]

 [[-0.176 -0.176 -0.   ]
  [-0.176 -0.    -0.176]
  [-0.    -0.176 -0.176]]

 [[-0.176 -0.176 -0.   ]
  [ 0.     0.     0.   ]
  [ 0.     0.     0.   ]]

 [[ 0.     0.     0.   ]
  [-0.176 -0.    -0.176]
  [ 0.     0.     0.   ]]

 [[ 0.     0.     0.   ]
  [ 0.     0.     0.   ]
  [-0.    -0.176 -0.176]]

 [[ 0.     0.     0.   ]
  [-0.176 -0.    -0.176]
  [-0.    -0.176 -0.176]]

 [[-0.176 -0.176 -0.   ]
  [ 0.     0.     0.   ]
  [-0.    -0.176 -0.176]]
